# Generated by Django 5.0.7 on 2025-10-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priece',
            new_name='price',
        ),
    ]
