# Generated by Django 5.2.7 on 2026-02-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0007_order_payment_method_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_pdf_email', models.BooleanField(default=False, help_text='Automatically send an email with the PDF invoice after chekcout.')),
                ('allow_pdf_download', models.BooleanField(default=False, help_text="Show the 'Download Invoice' button on the sucess page.")),
            ],
        ),
    ]
