# Generated by Django 5.2.7 on 2026-02-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0008_storesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name_plural': 'Store Settings'},
        ),
    ]
