# Generated by Django 6.0 on 2026-03-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Direct Bank Transfer', max_length=100),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='allow_pdf_download',
            field=models.BooleanField(default=False, help_text="Show the 'Download Invoice' button on the success page."),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='send_pdf_email',
            field=models.BooleanField(default=False, help_text='Automatically send an email with the PDF invoice after checkout.'),
        ),
    ]
